name: "EK GoDoc Action"
description: "Action for invoking documentation generation on pkg.go.dev"
author: "ESSENTIALKAOS"

branding:
  icon: "book"  
  color: "white"

inputs:
  domain: 
    description: "Source domain"
    required: false
    default: "github.com"

runs:
  using: "composite"
  steps:
    - id: gosum-req
      shell: bash
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]] ; then
          full_ver=$(echo ${GITHUB_REF} | cut -f3 -d'/')
          major_ver=$(echo ${full_ver} | cut -f1 -d'.')

          if [[ ${major_ver} != "v0" && ${major_ver} != "v1" ]] ; then
            full_ver_tag="${full_ver}+incompatible"
            import_path="${{github.repository}}/${major_ver}"
          else
            full_ver_tag="${full_ver}"
            import_path="${{github.repository}}"
          fi

          echo "URL: https://sum.golang.org/lookup/${{inputs.domain}}/${{github.repository}}@${full_ver_tag}"
          curl -s -m 10 https://sum.golang.org/lookup/${{inputs.domain}}/${{github.repository}}@${full_ver_tag} || exit 0

          echo "URL: https://sum.golang.org/lookup/${{inputs.domain}}/${import_path}@${full_ver}"
          curl -s -m 10 https://sum.golang.org/lookup/${{inputs.domain}}/${import_path}@${full_ver} || exit 0
        fi

    - id: pgkgodev-req
      shell: bash
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]] ; then
          full_ver=$(echo ${GITHUB_REF} | cut -f3 -d'/')
          major_ver=$(echo ${full_ver} | cut -f1 -d'.')

          if [[ ${major_ver} != "v0" && ${major_ver} != "v1" ]] ; then
            full_ver_tag="${full_ver}+incompatible"
            import_path="${{github.repository}}/${major_ver}"
          else
            full_ver_tag="${full_ver}"
            import_path="${{github.repository}}"
          fi

          echo "URL: https://pkg.go.dev/fetch/${{inputs.domain}}/${{github.repository}}@${full_ver_tag}"
          curl -s -m 5 -X POST https://pkg.go.dev/fetch/${{inputs.domain}}/${{github.repository}}@${full_ver_tag} || exit 0

          echo "URL: https://pkg.go.dev/fetch/${{inputs.domain}}/${import_path}@${full_ver}"
          curl -s -m 5 -X POST https://pkg.go.dev/fetch/${{inputs.domain}}/${import_path}@${full_ver} || exit 0
        fi
